### ISSUE TITLE
Does not work with terraform-kubernetes-provider-alpha

### ISSUE THREAD

**Issue by Starefossen** [banzaicloud/istio-operator#445]
**Describe the bug**

This operator does not currently work with the new [terraform-kubernetes-provider-alpha](https://github.com/hashicorp/terraform-provider-kubernetes-alpha) which uses the `kubectl dry-run=server` which is gives the following error on terraform apply:

```
Error: rpc error: code = Unknown desc = update dry-run for 'istio-system/istio' failed: admission webhook "istio.validation.banzaicloud.io" does not support dry run
```

Setting `sideEffects: None` to the `validatingwebhookconfigurations/istio-operator-webhook` appears to mitigate this issue.

Related issue: https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/49                                                                         

**Steps to reproduce the issue:**
Please describe the steps to reproduce the issue.

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem like release numberm version, branch, etc.

**Comment by Laci21** [comment]
#442 should solve this issue, see specifically this commit: https://github.com/banzaicloud/istio-operator/pull/442/commits/f2da8135c6457b82957853ed49e71b481800d671

**Comment by Starefossen** [comment]
Fantastic @Laci21 🤩

**Comment by Laci21** [comment]
@Starefossen, this landed in docker image version `0.6.2`, helm chart version `0.0.51`.

**Comment by Starefossen** [comment]
Awesome 🤩

**Comment by vsychov** [comment]
Hi guys, it looks like this is still reproducible, I made PR with fix: #556
